apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapicloudtest2-deployment
  labels:
    app: WebApiCloudTest2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WebApiCloudTest2	  
  template:
    metadata:
      labels:
        app: WebApiCloudTest2
    spec:
      containers:
      - name: webapicloudtest2
        image: seshacr.azurecr.io/webapicloudtest2dockerimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisec2
---
apiVersion: v1
kind: Service
metadata:
  name: webapicloudtestservice2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: WebApiCloudTest2